import {
  nike_air_max_270,
  nike_air_zoom_AIR,
  nike_air_max_90,
  nike_blazer_mid_77,
  Nike_air_force_107,
  nike_react_miler,
  nike_bassi_jdi,
  nike_air_max_terrace_cape90,
  nike_pegasus_trail_3,
  Nike_air_force_1_fantanka,
  nike_air_huarache,
  nike_court_legacy,
  nike_air_max_90_ltr,
  nike_point_lane,
  nike_air_max_2021,
  nike_sunday_protect,
  nike_revolution_6_se,
  nike_blazer_next_nature,
} from "./db-assets/index";

export const products = [
  // mens category
  {
    _id: "dfadfadf",
    productName: "Nike Air Max 270",
    price: 8999,
    image: nike_air_max_270,
    categoryName: "man",
    discount: 30,
    latest: true,
    rating: 3,
  },
  {
    _id: "adfadfa",
    productName: "Nike Air Zoom 38 A.I.R.",
    price: 9100,
    image: nike_air_zoom_AIR,
    categoryName: "man",
    discount: 20,
    latest: false,
    rating: 4,
  },
  {
    _id: "haadfadgh",
    productName: "Nike Air Max 90",
    price: 7000,
    image: nike_air_max_90,
    categoryName: "man",
    discount: 40,
    latest: true,
    rating: 2,
  },
  {
    _id: "gdfadgtjrg",
    productName: "Nike Blazer Mid '77",
    price: 6500,
    image: nike_blazer_mid_77,
    categoryName: "man",
    discount: 10,
    latest: true,
    rating: 3,
  },
  {
    _id: "sghfgarthtgnf",
    productName: "Nike Air  Force 1 07",
    price: 8000,
    image: Nike_air_force_107,
    categoryName: "man",
    discount: 15,
    latest: false,
    rating: 4,
  },
  {
    _id: "affhthtd",
    productName: "Nike React Miler 2 Shiield",
    price: 7599,
    image: nike_react_miler,
    categoryName: "man",
    discount: 10,
    latest: true,
    rating: 5,
  },
  {
    _id: "hjytaetadf",
    productName: "Nike Bassi JDI",
    price: 1000,
    image: nike_bassi_jdi,
    categoryName: "man",
    discount: 12,
    latest: true,
    rating: 4,
  },
  {
    _id: "ghtrhad",
    productName: "Nike Air Max Terrace 90",
    price: 9999,
    image: nike_air_max_terrace_cape90,
    categoryName: "man",
    discount: 25,
    latest: false,
    rating: 3,
  },
  // womesn category
  {
    _id: "gnzdfvarg",
    productName: "Nike Blazer Next Nature",
    price: 6999,
    image: nike_blazer_next_nature,
    categoryName: "women",
    discount: 22,
    latest: false,
    rating: 2,
  },
  {
    _id: "hthadfdvb",
    productName: "Nike Pegasus trail 3",
    price: 7500,
    image: nike_pegasus_trail_3,
    categoryName: "women",
    discount: 22,
    latest: true,
    rating: 3,
  },
  {
    _id: "hbfgadfar",
    productName: "Nike Air Force 1 Fantanka",
    price: 9000,
    image: Nike_air_force_1_fantanka,
    categoryName: "women",
    discount: 33,
    latest: true,
    rating: 4,
  },
  {
    _id: "nhrtgyhcv",
    productName: "Nike Air Huarache",
    price: 8500,
    image: nike_air_huarache,
    categoryName: "women",
    discount: 30,
    latest: false,
    rating: 5,
  },
  {
    _id: "tyhagffb",
    productName: "Nike Court Legacy Serena",
    price: 3000,
    image: nike_court_legacy,
    categoryName: "women",
    discount: 26,
    latest: false,
    rating: 2,
  },
  // kids category
  {
    _id: "hargtrhfhvdf",
    productName: "Nike Air Max 90 LTR",
    price: 6495,
    image: nike_air_max_90_ltr,
    categoryName: "kid",
    discount: 12,
    latest: true,
    rating: 1,
  },
  {
    _id: "rtgyhfvarfg",
    productName: "Nike Point Lane",
    price: 7999,
    image: nike_point_lane,
    categoryName: "kid",
    discount: 32,
    latest: true,
    rating: 3,
  },
  {
    _id: "afrgafgaaf",
    productName: "Nike Air Max 2021",
    price: 7500,
    image: nike_air_max_2021,
    categoryName: "kid",
    discount: 28,
    latest: false,
    rating: 4,
  },
  {
    _id: "jytjgssfgfg",
    productName: "Nike Sunday Protect 3",
    price: 2995,
    image: nike_sunday_protect,
    categoryName: "kid",
    discount: 31,
    latest: true,
    rating: 2,
  },
  {
    _id: "ytghfsathfb",
    productName: "Nike Revolution 6 SE",
    price: 3495,
    image: nike_revolution_6_se,
    categoryName: "kid",
    discount: 27,
    latest: true,
    rating: 5,
  },
];
