export { Home } from "./homePage/home";
export { Login } from "./authPage/login";
export { SignUp } from "./authPage/signup";
export { Wishlist } from "./wishlistPage/wishlist";
export { Cart } from "./cartPage/cart";
export { Product } from "./productPage/product";
export { Order } from "./orderPage/order";
export { Profile } from "./profilePage/profile";
export { SingleProduct } from "./singleProduct/singleProduct";
